apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
  name: "{{ include "robotShop.fullname" . }}-mongodb"
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
