apiVersion: v1
kind: Service
metadata:
  name: {{ include "robotShop.fullname" . }}
  labels:
    service: user
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: user
